/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from './about.css.shim.ngstyle';
import * as i1 from '@angular/core';
import * as i2 from '../../../app/about/about.component';
const styles_AboutComponent:any[] = [i0.styles];
export const RenderType_AboutComponent:i1.RendererType2 = i1.ɵcrt({encapsulation:0,
    styles:styles_AboutComponent,data:{}});
export function View_AboutComponent_0(_l:any):i1.ɵViewDefinition {
  return i1.ɵvid(0,[(_l()(),i1.ɵeld(0,(null as any),(null as any),16,'div',[['class',
      'panel panel-info']],(null as any),(null as any),(null as any),(null as any),
      (null as any))),(_l()(),i1.ɵted((null as any),['\n  '])),(_l()(),i1.ɵeld(0,(null as any),
      (null as any),4,'div',[['class','panel-heading']],(null as any),(null as any),
      (null as any),(null as any),(null as any))),(_l()(),i1.ɵted((null as any),['\n    '])),
      (_l()(),i1.ɵeld(0,(null as any),(null as any),1,'h3',[['class','panel-title']],
          (null as any),(null as any),(null as any),(null as any),(null as any))),
      (_l()(),i1.ɵted((null as any),['About'])),(_l()(),i1.ɵted((null as any),['\n  '])),
      (_l()(),i1.ɵted((null as any),['\n  '])),(_l()(),i1.ɵeld(0,(null as any),(null as any),
          7,'div',[['class','panel-body']],(null as any),(null as any),(null as any),
          (null as any),(null as any))),(_l()(),i1.ɵted((null as any),['\n      This application has been written by developers at NMD.'])),
      (_l()(),i1.ɵeld(0,(null as any),(null as any),0,'br',([] as any[]),(null as any),
          (null as any),(null as any),(null as any),(null as any))),(_l()(),i1.ɵeld(0,
          (null as any),(null as any),0,'br',([] as any[]),(null as any),(null as any),
          (null as any),(null as any),(null as any))),(_l()(),i1.ɵted((null as any),
          ['\n\n      If you have any problems contact us at '])),(_l()(),i1.ɵeld(0,
          (null as any),(null as any),1,'mark',([] as any[]),(null as any),(null as any),
          (null as any),(null as any),(null as any))),(_l()(),i1.ɵted((null as any),
          ['datahjelp@imr.no'])),(_l()(),i1.ɵted((null as any),['.\n  '])),(_l()(),
          i1.ɵted((null as any),['\n'])),(_l()(),i1.ɵted((null as any),['\n']))],(null as any),
      (null as any));
}
export function View_AboutComponent_Host_0(_l:any):i1.ɵViewDefinition {
  return i1.ɵvid(0,[(_l()(),i1.ɵeld(0,(null as any),(null as any),1,'ng-component',
      ([] as any[]),(null as any),(null as any),(null as any),View_AboutComponent_0,
      RenderType_AboutComponent)),i1.ɵdid(49152,(null as any),0,i2.AboutComponent,
      ([] as any[]),(null as any),(null as any))],(null as any),(null as any));
}
export const AboutComponentNgFactory:i1.ComponentFactory<i2.AboutComponent> = i1.ɵccf('ng-component',
    i2.AboutComponent,View_AboutComponent_Host_0,{},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiQzovVXNlcnMva2pldGlsZi9Eb2N1bWVudHMvZ2l0bmV3L2FwcGxpY2F0aW9ucy9jcnVpc2UvZnJvbnRlbmQvc3JjL2FwcC9hYm91dC9hYm91dC5jb21wb25lbnQubmdmYWN0b3J5LnRzIiwidmVyc2lvbiI6Mywic291cmNlUm9vdCI6IiIsInNvdXJjZXMiOlsibmc6Ly8vQzovVXNlcnMva2pldGlsZi9Eb2N1bWVudHMvZ2l0bmV3L2FwcGxpY2F0aW9ucy9jcnVpc2UvZnJvbnRlbmQvc3JjL2FwcC9hYm91dC9hYm91dC5jb21wb25lbnQudHMiLCJuZzovLy9DOi9Vc2Vycy9ramV0aWxmL0RvY3VtZW50cy9naXRuZXcvYXBwbGljYXRpb25zL2NydWlzZS9mcm9udGVuZC9zcmMvYXBwL2Fib3V0L2Fib3V0Lmh0bWwiLCJuZzovLy9DOi9Vc2Vycy9ramV0aWxmL0RvY3VtZW50cy9naXRuZXcvYXBwbGljYXRpb25zL2NydWlzZS9mcm9udGVuZC9zcmMvYXBwL2Fib3V0L2Fib3V0LmNvbXBvbmVudC50cy5BYm91dENvbXBvbmVudF9Ib3N0Lmh0bWwiXSwic291cmNlc0NvbnRlbnQiOlsiICIsIjxkaXYgY2xhc3M9XCJwYW5lbCBwYW5lbC1pbmZvXCI+XG4gIDxkaXYgY2xhc3M9XCJwYW5lbC1oZWFkaW5nXCI+XG4gICAgPGgzIGNsYXNzPVwicGFuZWwtdGl0bGVcIj5BYm91dDwvaDM+XG4gIDwvZGl2PlxuICA8ZGl2IGNsYXNzPVwicGFuZWwtYm9keVwiPlxuICAgICAgVGhpcyBhcHBsaWNhdGlvbiBoYXMgYmVlbiB3cml0dGVuIGJ5IGRldmVsb3BlcnMgYXQgTk1ELjxici8+PGJyLz5cblxuICAgICAgSWYgeW91IGhhdmUgYW55IHByb2JsZW1zIGNvbnRhY3QgdXMgYXQgPG1hcms+ZGF0YWhqZWxwQGltci5ubzwvbWFyaz4uXG4gIDwvZGl2PlxuPC9kaXY+XG4iLCI8bmctY29tcG9uZW50PjwvbmctY29tcG9uZW50PiJdLCJtYXBwaW5ncyI6IkFBQUE7Ozs7Ozs7Ozs7Ozs7OztvQkNBQTtNQUFBO01BQUEsZ0JBQThCLHlDQUM1QjtNQUFBO01BQUEsNENBQTJCO01BQ3pCO1VBQUE7TUFBd0IsMENBQVU7TUFDOUIseUNBQ047VUFBQTtVQUFBLDhCQUF3QjtNQUNtQztVQUFBLDBEQUFLO1VBQUE7VUFBQSw0Q0FBSztVQUFBLHdEQUUxQjtVQUFBO1VBQUEsNENBQU07VUFBQSx1QkFBdUIsMENBQ2xFO2lCQUFBLHdCQUNGOzs7O29CQ1ROO01BQUE7K0JBQUEsVUFBQTtNQUFBOzs7In0=
