/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '@angular/core';
import * as i1 from '../../../app/lookups/lookups.module';
import * as i2 from '@angular/http';
import * as i3 from '../../../app/lookups/config.service';
import * as i4 from '../../../app/lookups/csrrole-dropdown.service';
import * as i5 from '../../../app/lookups/datatype-dropdown.service';
import * as i6 from '../../../app/lookups/collectedstatus-dropdown.service';
import * as i7 from '../../../app/lookups/seaarea-dropdown.service';
import * as i8 from '../../../app/lookups/csrunit-dropdown.service';
import * as i9 from '../../../app/lookups/csrsampletype-dropdown.service';
import * as i10 from '../../../app/lookups/csrsamplegroup-dropdown.service';
import * as i11 from '../../../app/lookups/platformcodesys-dropdown.service';
import * as i12 from '../../../app/lookups/cruiseseries-dropdown.service';
import * as i13 from '../../../app/lookups/institution-dropdown.service';
import * as i14 from '../../../app/lookups/nation-dropdown.service';
import * as i15 from '../../../app/lookups/platformtype-dropdown.service';
import * as i16 from '../../../app/lookups/missiontype-dropdown.service';
import * as i17 from '../../../app/lookups/project-dropdown.service';
import * as i18 from '../../../app/lookups/cruisestatus-dropdown.service';
import * as i19 from '../../../app/lookups/language-dropdown.service';
export const LookupsModuleNgFactory:i0.NgModuleFactory<i1.LookupsModule> = i0.ɵcmf(i1.LookupsModule,
    ([] as any[]),(_l:any) => {
      return i0.ɵmod([i0.ɵmpd(512,i0.ComponentFactoryResolver,i0.ɵCodegenComponentFactoryResolver,
          [[8,([] as any[])],[3,i0.ComponentFactoryResolver],i0.NgModuleRef]),i0.ɵmpd(4608,
          i2.BrowserXhr,i2.BrowserXhr,([] as any[])),i0.ɵmpd(4608,i2.ResponseOptions,
          i2.BaseResponseOptions,([] as any[])),i0.ɵmpd(5120,i2.XSRFStrategy,i2.ɵb,
          ([] as any[])),i0.ɵmpd(4608,i2.XHRBackend,i2.XHRBackend,[i2.BrowserXhr,i2.ResponseOptions,
          i2.XSRFStrategy]),i0.ɵmpd(4608,i2.RequestOptions,i2.BaseRequestOptions,([] as any[])),
          i0.ɵmpd(5120,i2.Http,i2.ɵc,[i2.XHRBackend,i2.RequestOptions]),i0.ɵmpd(4608,
              i3.ConfigService,i3.ConfigService,[i2.Http]),i0.ɵmpd(4608,i4.CSRRoleDropdownService,
              i4.CSRRoleDropdownService,[i2.Http,i3.ConfigService]),i0.ɵmpd(4608,i5.DatatypeDropdownService,
              i5.DatatypeDropdownService,[i2.Http,i3.ConfigService]),i0.ɵmpd(4608,
              i6.CollectedStatusDropdownService,i6.CollectedStatusDropdownService,
              [i2.Http,i3.ConfigService]),i0.ɵmpd(4608,i7.SeaareaDropdownService,i7.SeaareaDropdownService,
              [i2.Http,i3.ConfigService]),i0.ɵmpd(4608,i8.CSRUnitDropdownService,i8.CSRUnitDropdownService,
              [i2.Http,i3.ConfigService]),i0.ɵmpd(4608,i9.CSRSampleTypeDropdownService,
              i9.CSRSampleTypeDropdownService,[i2.Http,i3.ConfigService]),i0.ɵmpd(4608,
              i10.CSRSampleGroupDropdownService,i10.CSRSampleGroupDropdownService,
              [i2.Http,i3.ConfigService]),i0.ɵmpd(4608,i11.PlatformcodesysDropdownService,
              i11.PlatformcodesysDropdownService,[i2.Http,i3.ConfigService]),i0.ɵmpd(4608,
              i12.CruiseseriesDropdownService,i12.CruiseseriesDropdownService,[i2.Http,
                  i3.ConfigService]),i0.ɵmpd(4608,i13.InstitutionDropdownService,i13.InstitutionDropdownService,
              [i2.Http,i3.ConfigService]),i0.ɵmpd(4608,i14.NationDropdownService,i14.NationDropdownService,
              [i2.Http,i3.ConfigService]),i0.ɵmpd(4608,i15.PlatformTypeDropdownService,
              i15.PlatformTypeDropdownService,[i2.Http,i3.ConfigService]),i0.ɵmpd(4608,
              i16.MissiontypeDropdownService,i16.MissiontypeDropdownService,[i2.Http,
                  i3.ConfigService]),i0.ɵmpd(4608,i17.ProjectDropdownService,i17.ProjectDropdownService,
              [i2.Http,i3.ConfigService]),i0.ɵmpd(4608,i18.CruisestatusDropdownService,
              i18.CruisestatusDropdownService,[i2.Http,i3.ConfigService]),i0.ɵmpd(4608,
              i19.LanguageDropdownService,i19.LanguageDropdownService,[i2.Http,i3.ConfigService]),
          i0.ɵmpd(512,i2.HttpModule,i2.HttpModule,([] as any[])),i0.ɵmpd(512,i1.LookupsModule,
              i1.LookupsModule,([] as any[]))]);
    });
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiQzovVXNlcnMva2pldGlsZi9Eb2N1bWVudHMvZ2l0bmV3L2FwcGxpY2F0aW9ucy9jcnVpc2UvZnJvbnRlbmQvc3JjL2FwcC9sb29rdXBzL2xvb2t1cHMubW9kdWxlLm5nZmFjdG9yeS50cyIsInZlcnNpb24iOjMsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIm5nOi8vL0M6L1VzZXJzL2tqZXRpbGYvRG9jdW1lbnRzL2dpdG5ldy9hcHBsaWNhdGlvbnMvY3J1aXNlL2Zyb250ZW5kL3NyYy9hcHAvbG9va3Vwcy9sb29rdXBzLm1vZHVsZS50cyJdLCJzb3VyY2VzQ29udGVudCI6WyIgIl0sIm1hcHBpbmdzIjoiQUFBQTs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7OyJ9
