/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


export const styles:any[] = ['@charset "UTF-8";\r\n\r\nhtml[_ngcontent-%COMP%] {\r\n    position: relative;\r\n    min-height: 100%;\r\n}\r\nbody[_ngcontent-%COMP%] {\r\n    width: 100%;\r\n    margin-bottom: 60px;\r\n    margin-top: 0px;\r\n    font-size: 12;\r\n}\r\n.main[_ngcontent-%COMP%] {\r\n  margin-bottom: 60px;\r\n}\r\n@media (min-width: 1600px)\r\n.container {\r\n    width[_ngcontent-%COMP%]:   1570px[_ngcontent-%COMP%];\r\n}\r\n.navbar[_ngcontent-%COMP%] {\r\n    width: 100%;\r\n    height: 50px;\r\n    padding-left: 15px;\r\n    padding-right: 15px;\r\n    margin-bottom: 0px;\r\n    background-color: dodgerblue;\r\n    color: white;\r\n}\r\n.navbar-default[_ngcontent-%COMP%]   .navbar-brand[_ngcontent-%COMP%] {\r\n    color: white;\r\n}\r\n.navbar-default[_ngcontent-%COMP%]   .navbar-nav[_ngcontent-%COMP%]    > li[_ngcontent-%COMP%]    > a[_ngcontent-%COMP%] {\r\n    color: white;\r\n}\r\n.footer[_ngcontent-%COMP%] {\r\n    position: fixed;\r\n    bottom: 0;\r\n    width: 100%;\r\n    height: 60px;\r\n    background-color: #f5f5f5;\r\n    padding: 10px;\r\n}'];
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiQzovVXNlcnMva2pldGlsZi9Eb2N1bWVudHMvZ2l0bmV3L2FwcGxpY2F0aW9ucy9jcnVpc2UvZnJvbnRlbmQvc3JjL2FwcC9ob21lL2hvbWUuY3NzLnNoaW0ubmdzdHlsZS50cyIsInZlcnNpb24iOjMsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIm5nOi8vL0M6L1VzZXJzL2tqZXRpbGYvRG9jdW1lbnRzL2dpdG5ldy9hcHBsaWNhdGlvbnMvY3J1aXNlL2Zyb250ZW5kL3NyYy9hcHAvaG9tZS9ob21lLmNzcyJdLCJzb3VyY2VzQ29udGVudCI6WyIgIl0sIm1hcHBpbmdzIjoiQUFBQTs7Ozs7Ozs7In0=
