/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


export const styles:any[] = ['.breadcrumb[_ngcontent-%COMP%] {\n    width: 100%;\n    height: 30px;\n    margin-bottom: 0px;\n}\n.breadcrumb-container[_ngcontent-%COMP%] {\n    width: 100%;\n    margin-bottom: 10px;\n    height: 30px;\n}\n.breadcrumb-container[_ngcontent-%COMP%]    > .container-fluid[_ngcontent-%COMP%] {\n    padding-left: 0px;\n    padding-right: 0px;\n}'];
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiQzovVXNlcnMva2pldGlsZi9Eb2N1bWVudHMvZ2l0bmV3L2FwcGxpY2F0aW9ucy9jcnVpc2UvZnJvbnRlbmQvc3JjL2FwcC9icmVhZGNydW1iL2JyZWFkY3J1bWIuY3NzLnNoaW0ubmdzdHlsZS50cyIsInZlcnNpb24iOjMsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIm5nOi8vL0M6L1VzZXJzL2tqZXRpbGYvRG9jdW1lbnRzL2dpdG5ldy9hcHBsaWNhdGlvbnMvY3J1aXNlL2Zyb250ZW5kL3NyYy9hcHAvYnJlYWRjcnVtYi9icmVhZGNydW1iLmNzcyJdLCJzb3VyY2VzQ29udGVudCI6WyIgIl0sIm1hcHBpbmdzIjoiQUFBQTs7Ozs7Ozs7In0=
