/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from './breadcrumb.css.shim.ngstyle';
import * as i1 from '@angular/core';
import * as i2 from '@angular/router';
import * as i3 from '@angular/common';
import * as i4 from '../../../app/breadcrumb/breadcrumb.component';
const styles_BreadcrumbComponent:any[] = [i0.styles];
export const RenderType_BreadcrumbComponent:i1.RendererType2 = i1.ɵcrt({encapsulation:0,
    styles:styles_BreadcrumbComponent,data:{}});
function View_BreadcrumbComponent_1(_l:any):i1.ɵViewDefinition {
  return i1.ɵvid(0,[(_l()(),i1.ɵeld(0,(null as any),(null as any),6,'li',([] as any[]),
      (null as any),(null as any),(null as any),(null as any),(null as any))),(_l()(),
      i1.ɵeld(0,(null as any),(null as any),5,'a',[['routerLinkActive','active']],
          [[1,'target',0],[8,'href',4]],[[(null as any),'click']],(_v,en,$event) => {
            var ad:boolean = true;
            if (('click' === en)) {
              const pd_0:any = ((<any>i1.ɵnov(_v,2).onClick($event.button,$event.ctrlKey,
                  $event.metaKey,$event.shiftKey)) !== false);
              ad = (pd_0 && ad);
            }
            return ad;
          },(null as any),(null as any))),i1.ɵdid(671744,[[2,4]],0,i2.RouterLinkWithHref,
      [i2.Router,i2.ActivatedRoute,i3.LocationStrategy],{routerLink:[0,'routerLink']},
      (null as any)),i1.ɵdid(1720320,(null as any),2,i2.RouterLinkActive,[i2.Router,
      i1.ElementRef,i1.Renderer,i1.ChangeDetectorRef],{routerLinkActive:[0,'routerLinkActive']},
      (null as any)),i1.ɵqud(603979776,1,{links:1}),i1.ɵqud(603979776,2,{linksWithHrefs:1}),
      (_l()(),i1.ɵted((null as any),['','']))],(_ck,_v) => {
    const currVal_2:any = i1.ɵinlineInterpolate(1,'',_v.context.$implicit.url,'');
    _ck(_v,2,0,currVal_2);
    const currVal_3:any = 'active';
    _ck(_v,3,0,currVal_3);
  },(_ck,_v) => {
    const currVal_0:any = i1.ɵnov(_v,2).target;
    const currVal_1:any = i1.ɵnov(_v,2).href;
    _ck(_v,1,0,currVal_0,currVal_1);
    const currVal_4:any = _v.context.$implicit.name;
    _ck(_v,6,0,currVal_4);
  });
}
export function View_BreadcrumbComponent_0(_l:any):i1.ɵViewDefinition {
  return i1.ɵvid(0,[(_l()(),i1.ɵeld(0,(null as any),(null as any),10,'div',[['class',
      'panel panel-default breadcrumb-container']],(null as any),(null as any),(null as any),
      (null as any),(null as any))),(_l()(),i1.ɵted((null as any),['\n    '])),(_l()(),
      i1.ɵeld(0,(null as any),(null as any),7,'div',[['class','container-fluid']],
          (null as any),(null as any),(null as any),(null as any),(null as any))),
      (_l()(),i1.ɵted((null as any),['\n      '])),(_l()(),i1.ɵeld(0,(null as any),
          (null as any),4,'ol',[['class','breadcrumb']],(null as any),(null as any),
          (null as any),(null as any),(null as any))),(_l()(),i1.ɵted((null as any),
          ['\n          '])),(_l()(),i1.ɵand(16777216,(null as any),(null as any),
          1,(null as any),View_BreadcrumbComponent_1)),i1.ɵdid(802816,(null as any),
          0,i3.NgForOf,[i1.ViewContainerRef,i1.TemplateRef,i1.IterableDiffers],{ngForOf:[0,
              'ngForOf']},(null as any)),(_l()(),i1.ɵted((null as any),['\n      '])),
      (_l()(),i1.ɵted((null as any),['\n    '])),(_l()(),i1.ɵted((null as any),['\n'])),
      (_l()(),i1.ɵted((null as any),['\n']))],(_ck,_v) => {
    var _co:i4.BreadcrumbComponent = _v.component;
    const currVal_0:any = _co.breadcrumbs;
    _ck(_v,7,0,currVal_0);
  },(null as any));
}
export function View_BreadcrumbComponent_Host_0(_l:any):i1.ɵViewDefinition {
  return i1.ɵvid(0,[(_l()(),i1.ɵeld(0,(null as any),(null as any),1,'breadcrumbComponent',
      ([] as any[]),(null as any),(null as any),(null as any),View_BreadcrumbComponent_0,
      RenderType_BreadcrumbComponent)),i1.ɵdid(114688,(null as any),0,i4.BreadcrumbComponent,
      [i2.Router],(null as any),(null as any))],(_ck,_v) => {
    _ck(_v,1,0);
  },(null as any));
}
export const BreadcrumbComponentNgFactory:i1.ComponentFactory<i4.BreadcrumbComponent> = i1.ɵccf('breadcrumbComponent',
    i4.BreadcrumbComponent,View_BreadcrumbComponent_Host_0,{},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiQzovVXNlcnMva2pldGlsZi9Eb2N1bWVudHMvZ2l0bmV3L2FwcGxpY2F0aW9ucy9jcnVpc2UvZnJvbnRlbmQvc3JjL2FwcC9icmVhZGNydW1iL2JyZWFkY3J1bWIuY29tcG9uZW50Lm5nZmFjdG9yeS50cyIsInZlcnNpb24iOjMsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIm5nOi8vL0M6L1VzZXJzL2tqZXRpbGYvRG9jdW1lbnRzL2dpdG5ldy9hcHBsaWNhdGlvbnMvY3J1aXNlL2Zyb250ZW5kL3NyYy9hcHAvYnJlYWRjcnVtYi9icmVhZGNydW1iLmNvbXBvbmVudC50cyIsIm5nOi8vL0M6L1VzZXJzL2tqZXRpbGYvRG9jdW1lbnRzL2dpdG5ldy9hcHBsaWNhdGlvbnMvY3J1aXNlL2Zyb250ZW5kL3NyYy9hcHAvYnJlYWRjcnVtYi9icmVhZGNydW1iLmh0bWwiLCJuZzovLy9DOi9Vc2Vycy9ramV0aWxmL0RvY3VtZW50cy9naXRuZXcvYXBwbGljYXRpb25zL2NydWlzZS9mcm9udGVuZC9zcmMvYXBwL2JyZWFkY3J1bWIvYnJlYWRjcnVtYi5jb21wb25lbnQudHMuQnJlYWRjcnVtYkNvbXBvbmVudF9Ib3N0Lmh0bWwiXSwic291cmNlc0NvbnRlbnQiOlsiICIsIjxkaXYgY2xhc3M9XCJwYW5lbCBwYW5lbC1kZWZhdWx0IGJyZWFkY3J1bWItY29udGFpbmVyXCI+XG4gICAgPGRpdiBjbGFzcz1cImNvbnRhaW5lci1mbHVpZFwiPlxuICAgICAgPG9sIGNsYXNzPVwiYnJlYWRjcnVtYlwiPlxuICAgICAgICAgIDxsaSAqbmdGb3I9XCJsZXQgYnJlYWRjcnVtYiBvZiBicmVhZGNydW1ic1wiPjxhIHJvdXRlckxpbms9XCJ7e2JyZWFkY3J1bWIudXJsfX1cIiByb3V0ZXJMaW5rQWN0aXZlPVwiYWN0aXZlXCI+e3ticmVhZGNydW1iLm5hbWV9fTwvYT48L2xpPlxuICAgICAgPC9vbD5cbiAgICA8L2Rpdj5cbjwvZGl2PlxuIiwiPGJyZWFkY3J1bWJDb21wb25lbnQ+PC9icmVhZGNydW1iQ29tcG9uZW50PiJdLCJtYXBwaW5ncyI6IkFBQUE7Ozs7Ozs7Ozs7Ozs7Ozs7O29CQ0dVO01BQUEsd0VBQTJDO2FBQUE7VUFBQTtZQUFBO1lBQUE7Y0FBQTtrQkFBQTtjQUFBO1lBQUE7WUFBQTtVQUFBLHVDQUFBO01BQUE7TUFBQSxzQkFBQTtvREFBQTtNQUFBO01BQTZEO0lBQTFEO0lBQUgsV0FBRyxTQUFIO0lBQW1DO0lBQW5DLFdBQW1DLFNBQW5DOztJQUFBO0lBQUE7SUFBQSxXQUFBLG1CQUFBO0lBQTZEO0lBQUE7Ozs7b0JBSGxIO01BQUE7TUFBQSw4QkFBc0QsMkNBQ2xEO2FBQUE7VUFBQTtNQUE2Qiw2Q0FDM0I7VUFBQTtVQUFBLDRDQUF1QjtVQUFBLG1CQUNuQjtVQUFBLG9EQUFBO1VBQUE7Y0FBQSwyQkFBb0k7TUFDbkksMkNBQ0Q7TUFDSjs7SUFIUTtJQUFKLFdBQUksU0FBSjs7OztvQkNIVjtNQUFBO29DQUFBLFVBQUE7TUFBQTtJQUFBOzs7OyJ9
