/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


export const styles:any[] = ['.ui-datepicker[_ngcontent-%COMP%]   select.ui-datepicker-year[_ngcontent-%COMP%] {\r\n  width: 100%;\r\n}\r\n\r\n.ui-datepicker[_ngcontent-%COMP%]   select.ui-datepicker-month[_ngcontent-%COMP%] {\r\n  width: 100%;\r\n}'];
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiQzovVXNlcnMva2pldGlsZi9Eb2N1bWVudHMvZ2l0bmV3L2FwcGxpY2F0aW9ucy9jcnVpc2UvZnJvbnRlbmQvc3JjL2FwcC9saXN0Y3J1aXNlcy9saXN0Y3J1aXNlLmNzcy5zaGltLm5nc3R5bGUudHMiLCJ2ZXJzaW9uIjozLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJuZzovLy9DOi9Vc2Vycy9ramV0aWxmL0RvY3VtZW50cy9naXRuZXcvYXBwbGljYXRpb25zL2NydWlzZS9mcm9udGVuZC9zcmMvYXBwL2xpc3RjcnVpc2VzL2xpc3RjcnVpc2UuY3NzIl0sInNvdXJjZXNDb250ZW50IjpbIiAiXSwibWFwcGluZ3MiOiJBQUFBOzs7Ozs7OzsifQ==
